services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - todo-data:/data
      - ./src:/app/src
    command: npm run dev

volumes:
  todo-data: