name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    if: github.repository == 'EpitechPGE45-2026/G-ING-900-PAR-9-1-legacy-6'
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
